name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Asegúrate de que esta sea la región correcta

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name SpringBootAppEduPlay \
            --deployment-group-name SpringBootDeploymentGroup \
            --github-location repository=TaraPadilla/EduPlay-Rewards,commitId=${{ github.sha }}
