name: Deploy to AWS CodeDeploy 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS CodeDeploy
        uses: uses: aws-actions/aws-codedeploy-github-action@v0.3.1
        with:
          application-name: "SpringBootAppEduPlay"  # Reemplaza con el nombre de tu aplicación en CodeDeploy
          deployment-group: "SpringBootDeploymentGroup"  # Reemplaza con el nombre de tu grupo de despliegue
          github-token: ${{ secrets.GITHUB_TOKEN }}
          region: "us-east-1"  # Asegúrate de que sea la misma región de tu instancia
